version: "3"
services:
  broker:
    image: mqtt/broker:latest
    restart: always
    ports: 
      - "1883:1883"
    networks:
      - mqtt-test
    volumes:
      - ./../log:/mosquitto/log
      - ./../data:/mosquitto/data
    command:
      - "sh"
      - "-c"
      - "tail -f /mosquitto/log/mosquitto.log"

  node-red:
    image: nodered/node-red:latest
    restart: always
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    networks:
      - mqtt-test

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
    networks:
      - mqtt-test

networks:
  mqtt-test: